language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jhonnatha/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jhonnatha/docker-react npm run test