language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jhonnatha/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jhonnatha/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-sa-east-1-012863680361"
  bucket_path: "docker-react"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY